export const MY_TREE_SUCCESS = 'MY_TREE_SUCCESS'
export const MY_TOP_LEVEL_SUCCESS = 'MY_TOP_LEVEL_SUCCESS'
export const ACTIVE_SMART_SPREADER_SUCCESS = 'ACTIVE_SMART_SPREADER_SUCCESS'
export const ALL_ACTIVE_SMART_SPREADER_SUCCESS = 'ALL_ACTIVE_SMART_SPREADER_SUCCESS'